# Generated by Django 4.0.2 on 2022-04-22 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='user_details.userdetail'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='user_details.userdetail'),
        ),
    ]
